output_bitrate: 192 # 128k, 192k or 320k
enrichments:
  discogs:
    discogs_token: XXX
  spotify:
    sp_client_id: XXX
    sp_client_secret: XXX
validations:
  mandatory_tags:
    - artist
    - album
    - title
  accepted_input_mime_types:
    - audio/mp3
    - audio/mp4
    - audio/flac
    - audio/m4a
  minimum_input_bitrate: 192 # 128, 192 or 320
normalization_headroom: 0.1 # Normalize audio at 90% of maximum
